#====================================================================================================
# This is free software, lisence use MIT.
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
#====================================================================================================
# Thanks:
#----------------------------------------------------------------------------------------------------
# <https://github.com/KFERMercer/OpenWrt-CI>
# <https://github.com/kiddin9/openwrt-packages/blob/master/.github/workflows/upstream.yml>
# https://github.com/Twinzo1/openwrt-packages/blob/main/.github/workflows/upstream.yml
#====================================================================================================
# third-party feed:
#--------------------------------------------------------------------------------------------------
# https://github.com/281677160/openwrt-package
#===================================================================================================
# 此仓库拉取编译所需要的openwrt源码软件包中没有或更优的源码,且为唯一的第三方feed.或者拉取编译不需要但是十分优秀的插件.
# Add a third-party software:git clone -b branch-name software-url
# Add a third-party software:git clone --depth=1 software-url
# Add a third-party software:svn co software-url(/trunk or branch/branch-name/software-name) 源码路径中的tree/master 替换成 trunk;源码路径中的tree/branch 替换成 branch/branch-name
# 拉取命令参考https://github.com/danshui-git/shuoming/blob/master/ming.md
#----------------------------------------------------------------------------------------------------

name: package update
on:
  push:
    paths:
      - '.github/workflows/Package updater.yml'
 # schedule:
 #   - cron: 0 */12 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  updatepackage:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "51288907+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
#=========================================================================================================== 
    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*"`
        git rm -r --cache *
      
        # 下载diy脚本
        svn co https://github.com/281677160/openwrt-package/trunk/feeds/packages/utils/filebrowser

        svn co https://github.com/Twinzo1/AdGuardHome/trunk/luci-app-adguardhome &
      
        svn co https://github.com/281677160/openwrt-package/trunk/feeds/luci/applications/luci-app-filebrowser
        
        git clone --depth 1 https://github.com/Porcat/luci-app-filetransfer
        git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
        
        #svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash &
        
        git clone --depth 1 https://github.com/zzsj0928/luci-app-pushbot
  
        svn co https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom/trunk/luci-theme-infinityfreedom
        
        git clone --depth 1 https://github.com/iwrt/luci-app-ikoolproxy
  
         

    
        
   


        
 
 
         
        
        
      
        

        
      
#===========================================================================================================       
    - name: Apply patches
      run: |
        #sed -i "s/\r//g" open-app-filter/src/appfilter_ubus.c
        #find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"

    - name: Modify
      run: |
        # 清理石像鬼插件
        rm -rf *gargoyle*
        # 清理重复或非必要文件
        rm -Rf */.git */.svn qt5 openwrt-{chinadns*,simple-obfs,v2ray-plugin,fullconenat,dnsforwarder} cups* subweb \
        mt-drivers coremark npc luci-app-{flowoffload,sfe,appfilter,unblockneteasemusic*,adbyby-plus,advancedsetting,softethervpn,chinadns,docker,samba4} fcgiwrap \
        ddns-scripts_{aliyun,dnspod} UnblockNeteaseMusicGo ipv6-helper adbyby ChinaDNS luci-theme-netgear
        
        
        
        rm -f subconverter/patches/010-missing-header.patch
        sed -i 's?../../luci.mk?$(TOPDIR)/feeds/luci/luci.mk?g' */Makefile
        sed -i 's?../../lang?$(TOPDIR)/feeds/packages/lang?g' */Makefile
        bash diy/create_acl_for_luci.sh -a || true
        bash diy/convert_translation.sh -a || true
        sed -i 's/ca-certificates/ca-bundle/g' */Makefile
        #sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        sed -i 's/@GHCODELOAD/https:\/\/codeload.github.com/' */Makefile
        find */luasrc/view/ -maxdepth 2 -name "*.htm" | xargs -i sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' {}
        find ./*/ -maxdepth 1 -name "Makefile" ! -path "*tinyfecvpn*" ! -path "*gowebdav*" | xargs -i sed -i "s/PKG_HASH:=.*/PKG_HASH:=skip/g" {}
        sed -i 's/SUBDIRS=/M=/g' */Makefile
        # sed -i 's/\(add ucitrack \(.*\)\)/\1\n\tservice \2 enable/g' luci-app*/root/etc/uci-defaults/*

    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
